Stock Management Software/website/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, session
from flask_login import login_required, current_user
from . import db
from .models import Item, User, Inventory, ForSale
from datetime import datetime, timedelta

views = Blueprint('views', __name__)

@views.route('/deletion', methods=['GET', 'POST'])
@login_required
def employee_deletion():
    if request.method == 'POST':
        employee_id_to_delete = request.form.get('delete')
        if employee_id_to_delete:
            user_to_delete = User.query.get(employee_id_to_delete)
            if user_to_delete:
                db.session.delete(user_to_delete)
                db.session.commit()
                flash(f'Employee {user_to_delete.first_name} deleted successfully!', category='success')
            else:
                flash('Invalid employee ID for deletion.', category='error')

    users = User.query.all()

    return render_template("employee_deletion.html", users=users, user=current_user)

@views.route('/items', methods=['GET', 'POST'])
@login_required
def items():
    if request.method == 'POST':
        item_name = request.form.get('itemName')
        price = request.form.get('price')
        manufacturer = request.form.get('manufacturer')

        if not item_name or not price or not manufacturer:
            flash('Please fill in all fields.', 'error')
        else:
            try:
                price = float(price)
            except ValueError:
                flash('Price must be a valid number.', 'error')
                return redirect(url_for('views.items'))

            new_item = Item(itemName=item_name, price=price, manufacturer=manufacturer, user_relationship=current_user)
            db.session.add(new_item)
            db.session.commit()

            flash('Item added successfully!', 'success')
            return redirect(url_for('views.items'))

    items = Item.query.all()

    return render_template("items.html", user=current_user, items=items)

@views.route('/delete_item', methods=['POST'])
@login_required
def delete_item():
    item_name = request.form.get('deleteItemName')
    manufacturer = request.form.get('deleteManufacturer')

    if not item_name or not manufacturer:
        flash('Please provide both item name and manufacturer for deletion.', 'error')
        return redirect(url_for('views.items'))

    item_to_delete = Item.query.filter_by(itemName=item_name, manufacturer=manufacturer).first()

    if item_to_delete:
        db.session.delete(item_to_delete)
        db.session.commit()
        flash(f'Successfully deleted item: {item_name} - {manufacturer}', 'success')
    else:
        flash(f'Item not found: {item_name} - {manufacturer}', 'error')

    return redirect(url_for('views.items'))

@views.route('/inventory', methods=['GET', 'POST'])
@login_required
def inventory():
    items = Item.query.all()
    inventory_items = Inventory.query.all()

    if request.method == 'POST':
        if 'itemSelect' in request.form:
            add_to_inventory()
            flash('Item added to inventory successfully!', 'success')
            return redirect(url_for('views.inventory'))

        elif 'deleteInventoryItemID' in request.form:
            inventory_item_id = request.form.get('deleteInventoryItemID')
            delete_item_from_inventory(inventory_item_id)
            flash('Item deleted from inventory successfully!', 'success')

        elif 'reduceQuantityItemID' in request.form:
            item_id = request.form.get('reduceQuantityItemID')
            quantity_to_reduce = request.form.get('reduceQuantity')
            reduce_quantity(item_id, quantity_to_reduce)
            flash('Quantity reduced successfully!', 'success')

    return render_template("inventory.html", items=items, inventory_items=inventory_items, user=current_user)

@views.route('/delete_item_from_inventory', methods=['POST'])
@login_required
def delete_item_from_inventory():
    inventory_item_id = request.form.get('deleteInventoryItemID')
    if inventory_item_id:
        delete_item_from_inventory_logic(inventory_item_id)
        flash('Item deleted from inventory successfully!', 'success')
    else:
        flash('Invalid inventory item ID for deletion.', 'error')

    return redirect(url_for('views.inventory'))

def delete_item_from_inventory_logic(inventory_item_id):
    inventory_item = Inventory.query.get(inventory_item_id)
    if inventory_item:
        db.session.delete(inventory_item)
        db.session.commit()

@views.route('/reduce_quantity', methods=['POST'])
@login_required
def reduce_quantity():
    item_id = request.form.get('itemID')
    quantity_to_reduce = request.form.get('quantity')
    if item_id and quantity_to_reduce:
        reduce_quantity_logic(item_id, quantity_to_reduce)
        flash('Quantity reduced successfully!', 'success')
    else:
        flash('Invalid item ID or quantity for reduction.', 'error')

    return redirect(url_for('views.inventory'))

def reduce_quantity_logic(item_id, quantity_to_reduce):
    item = Item.query.get(item_id)
    if item:
        inventory_item = Inventory.query.filter_by(item_id=item_id).first()
        if inventory_item and inventory_item.quantity >= int(quantity_to_reduce):
            inventory_item.quantity -= int(quantity_to_reduce)
            db.session.commit()
        else:
            flash('Invalid quantity for reduction.', 'error')
    else:
        flash('Invalid item ID for reduction.', 'error')

@views.route('/add_to_inventory', methods=['POST'])
@login_required
def add_to_inventory():
    item_id = request.form.get('itemSelect')
    quantity = request.form.get('quantity')

    if item_id and quantity:
        item = Item.query.get(item_id)

        if item:
            if int(quantity) > 0:
                inventory_item = Inventory.query.filter_by(item_id=item_id).first()

                if inventory_item:
                    # If the item is already in inventory, update the quantity
                    inventory_item.quantity += int(quantity)
                else:
                    # If the item is not in inventory, create a new entry
                    new_inventory_item = Inventory(item_id=item_id, quantity=int(quantity))
                    db.session.add(new_inventory_item)

                db.session.commit()
                flash('Item added to inventory successfully!', 'success')
            else:
                flash('Invalid quantity.', 'error')
        else:
            flash('Invalid item ID.', 'error')
    else:
        flash('Invalid form data.', 'error')

    return redirect(url_for('views.inventory'))

@views.route('/transfer', methods=['GET', 'POST'])
@login_required
def transfer():
    inventory_items = Inventory.query.all()

    if request.method == 'POST':
        selected_items_ids = [int(id) for id in request.form.getlist('selectedItems')]

        selected_items = []
        for item_id in selected_items_ids:
            quantity_key = f'quantity_{item_id}'
            quantity = int(request.form.get(quantity_key, 1))

            inventory_item = Inventory.query.get(item_id)

            if inventory_item:
                if inventory_item.quantity >= quantity:
                    selected_items.append({'inventory_item': inventory_item, 'quantity': quantity})
                else:
                    flash(f"Selected quantity for '{inventory_item.item.itemName}' exceeds available quantity in inventory.", 'error')

        if selected_items:
            flash('Selected items for transfer successfully!', 'success')

        return render_template("transfer.html", inventory_items=inventory_items, user=current_user, selected_items=selected_items)

    return render_template("transfer.html", inventory_items=inventory_items, user=current_user)


@views.route('/transfer_to_for_sale', methods=['POST'])
@login_required
def transfer_to_for_sale():
    selected_items_ids = request.form.getlist('selectedItems')

    for item_id in selected_items_ids:
        quantity_key = f'quantity_{item_id}'
        quantity = int(request.form.get(quantity_key, 1))

        inventory_item = Inventory.query.get(item_id)

        if inventory_item and inventory_item.quantity >= quantity:
            for_sale_item = ForSale.query.filter_by(inventory_id=inventory_item.id).first()
            
            if for_sale_item:
                #if item already exists, add quantity entered by user to it
                for_sale_item.quantity += quantity
            else:
                # If the item doesn't exist in the ForSale table, create a new entry
                for_sale_item = ForSale(quantity=quantity, inventory=inventory_item)
                db.session.add(for_sale_item)

            #reduce quantity in inventory by the amount the user entered
            inventory_item.quantity -= quantity  # Reduce quantity in inventory

            db.session.commit()
            flash('Items transferred to For Sale successfully!', 'success')
        else:
            flash('Invalid quantity for transfer.', 'error')

    return redirect(url_for('views.transfer'))


def commit_transfer_to_for_sale(selected_items_ids):
    for item_id in selected_items_ids:
        inventory_item = Inventory.query.get(item_id)

        if inventory_item and inventory_item.quantity > 0:
            # Get the transfer quantity from the form
            transfer_quantity_key = f'transferQuantity_{item_id}'
            transfer_quantity = int(request.form.get(transfer_quantity_key, 1))

            # Reduce quantity in inventory based on the transfer quantity
            inventory_item.quantity -= transfer_quantity

    db.session.commit()

@views.route('/for_sale', methods=['GET'])
@login_required
def for_sale():
    for_sale_items = ForSale.query.all()

    # Sorting the for sale items alphabetically using Merge Sort
    sorted_for_sale_items = merge_sort(for_sale_items)

    grouped_items = {}
    for sale_item in sorted_for_sale_items:

Stock Management Software/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.job_role == 'manager' and user.is_authenticated %}
          <a class="nav-item nav-link" id="employees" href="/">Sign Up</a>
          <a class="nav-item nav-link" id="deletion" href="/deletion">Employees</a>
          <a class="nav-item nav-link" id="promotion" href="/promotion">Promotion</a>
          <a class="nav-item nav-link" id="items" href="/items">Items</a>
          <a class="nav-item nav-link" id="inventory" href="/inventory">Inventory</a>
          <a class="nav-item nav-link" id="transfer" href="/transfer">Transfer</a>
          <a class="nav-item nav-link" id="forSale" href="/for_sale">For-Sale</a>
          <a class="nav-item nav-link" id="calculations" href="/calculations">Calculations</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% elif user.job_role == 'senior_staff' and user.is_authenticated %}
          <a class="nav-item nav-link" id="employees" href="/">Sign Up</a>
          <a class="nav-item nav-link" id="deletion" href="/deletion">Employees</a>
          <a class="nav-item nav-link" id="items" href="/items">Items</a>
          <a class="nav-item nav-link" id="inventory" href="/inventory">Inventory</a>
          <a class="nav-item nav-link" id="transfer" href="/transfer">Transfer</a>
          <a class="nav-item nav-link" id="forSale" href="/for_sale">For-Sale</a>
          <a class="nav-item nav-link" id="calculations" href="/calculations">Calculations</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% elif user.job_role == 'general_staff' and user.is_authenticated %}
          <a class="nav-item nav-link" id="forSale" href="/for_sale">For-Sale</a>
          <a class="nav-item nav-link" id="calculations" href="/calculations">Calculations</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="employees" href="/">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script>
      function confirmDeletion() {
        return confirm("Are you sure you want to delete this employee?");
      }
    </script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

Stock Management Software/website/templates/calculations.html
{% extends "base.html" %}

{% block title %}Calculations Page{% endblock %}

{% block content %}
  <h2 class="mt-4 mb-4">Calculations Page</h2>

  <div class="mt-4">
    <h4>Options:</h4>
    <ul>
      <li><a href="{{ url_for('views.demand_page') }}">Demand</a></li>
      <li><a href="{{ url_for('views.lead_time_page') }}">Lead Time</a></li> <!-- Added Lead Time button -->
    </ul>
  </div>
{% endblock %}

Stock Management Software/website/templates/demand.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    <label for="monday">Monday:</label>
    <input type="number" name="monday" id="monday"><br>
    
    <label for="tuesday">Tuesday:</label>
    <input type="number" name="tuesday" id="tuesday"><br>
    
    <label for="wednesday">Wednesday:</label>
    <input type="number" name="wednesday" id="wednesday"><br>
    
    <label for="thursday">Thursday:</label>
    <input type="number" name="thursday" id="thursday"><br>
    
    <label for="friday">Friday:</label>
    <input type="number" name="friday" id="friday"><br>
    
    <label for="saturday">Saturday:</label>
    <input type="number" name="saturday" id="saturday"><br>
    
    <label for="sunday">Sunday:</label>
    <input type="number" name="sunday" id="sunday"><br>
  
    <label for="current_stock">Current Stock Quantity:</label>
    <input type="number" name="current_stock" id="current_stock"><br>
  
    <button type="submit">Submit</button>
    <!-- Add an exit button to redirect back to calculations.html -->
    <a href="{{ url_for('views.calculations_page') }}" class="btn btn-secondary">Exit</a>
</form>

{% if average_demand_per_day is defined %}
    <p>Average Demand per Day: {{ average_demand_per_day }}</p>
    <p>{{ restock_recommendation }}</p>
{% endif %}
{% endblock %}

Stock Management Software/website/templates/employee_deletion.html
{% extends "base.html" %}

{% block title %}Employee Deletion{% endblock %}

{% block content %}
  <h3 align="center">Employee Deletion</h3>
  <ul class="list-group">
    {% for user in users %}
      <li class="list-group-item">
        {{ user.first_name }} - {{ user.email }} - {{user.job_role}}
        
        {% if current_user.is_authenticated and current_user.job_role == 'manager' %}
          <form method="POST" style="display: inline-block;" onsubmit="return confirmDelete('{{ user.first_name }}');">
            <button type="submit" class="btn btn-danger" name="delete" value="{{ user.id }}">Delete</button>
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>

  <script>
    function confirmDelete(employeeName) {
      return confirm('Are you sure you want to delete employee ' + employeeName + '?');
    }
  </script>
{% endblock %}

Stock Management Software/website/templates/employee_sign-up.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
        required
      />
    </div>

    <div class="form-group">
      <label for="firstName">First Name</label>
      <input
        type="text"
        class="form-control"
        id="firstName"
        name="firstName"
        placeholder="Enter first name"
        required
      />
    </div>

    <div class="form-group">
      <label for="jobRole">Job Role</label>
      <select class="form-control" id="jobRole" name="jobRole" required>
              <option value="manager">Manager</option>
              <option value="senior_staff">Senior Staff</option>
              <option value="general_staff">General Staff</option>
          {% if current_user.job_role == 'manager' %}
              <option value="manager">Manager</option>
              <option value="senior_staff">Senior Staff</option>
              <option value="general_staff">General Staff</option>
          {% elif current_user.job_role == 'senior_staff' %}
              <option value="senior_staff">Senior Staff</option>
              <option value="general_staff">General Staff</option>
          {% else %}
              <option value="general_staff">General Staff</option>
          {% endif %}
      </select>
  </div>
  

    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Enter password"
        required
      />
    </div>

    <div class="form-group">
      <label for="password2">Password (Confirm)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Confirm password"
        required
      />
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

Stock Management Software/website/templates/for_sale.html
{% extends "base.html" %}

{% block title %}For Sale Items{% endblock %}

{% block content %}
  <h2 class="mt-4 mb-4">For Sale Items</h2>

  <!-- For Sale Items Table -->
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Item Name (alphabetical order)</th>
        <th>Total Quantity</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for grouped_item in grouped_items %}
        <tr>
          <td>{{ grouped_item.item_name }}</td>
          <td>{{ grouped_item.total_quantity }}</td>
          <td>
            <form method="post" action="{{ url_for('views.sale_made', item_id=grouped_item.item_id) }}">
                <button type="submit" class="btn btn-success">Sale Made</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Stock Management Software/website/templates/inventory.html
{% extends "base.html" %}

{% block title %}Inventory{% endblock %}

{% block content %}
  <h2 class="mt-4 mb-4">Inventory Management</h2>

  <!-- Add Item to Inventory Form -->
  <form method="POST" action="{{ url_for('views.inventory') }}" class="mb-4">
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="itemSelect">Item Name</label>
        <select class="form-control" id="itemSelect" name="itemSelect" required>
          {% for item in items %}
            <option value="{{ item.id }}">{{ item.itemName }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-4">
        <label for="quantity">Quantity</label>
        <input type="number" class="form-control" id="quantity" name="quantity" required>
      </div>
    </div>
    <button type="submit" class="btn btn-success">Add to Inventory</button>
  </form>

  <!-- Display Items in Inventory with Delete Buttons -->
  <h3 class="mt-4 mb-4">Items in Inventory</h3>
  {% for inventory_item in inventory_items %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">{{ inventory_item.item.itemName }}</h5>
        <p class="card-text">
          Quantity: {{ inventory_item.quantity }} |
          Price: £{{ "{:.2f}".format(inventory_item.item.price) if inventory_item.item and inventory_item.item.price is not none else 'N/A' }} |
          Manufacturer: {{ inventory_item.item.manufacturer }}
        </p>
        <form method="POST" action="{{ url_for('views.delete_item_from_inventory') }}" class="d-inline">
          <input type="hidden" name="deleteInventoryItemID" value="{{ inventory_item.id }}">
          <button type="submit" class="btn btn-danger">Delete from Inventory</button>
        </form>

        <!-- Quantity Reduction Form -->
        <form method="POST" action="{{ url_for('views.reduce_quantity') }}" class="d-inline">
          <div class="form-row align-items-center">
            <div class="col-auto">
              <label class="sr-only" for="quantity">Quantity</label>
              <input type="number" class="form-control mb-2" id="quantity" name="quantity" placeholder="Reduce Quantity" required>
            </div>
            <div class="col-auto">
              <input type="hidden" name="itemID" value="{{ inventory_item.item.id }}">
              <button type="submit" class="btn btn-secondary mb-2">Reduce Quantity</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  {% endfor %}
{% endblock %}

Stock Management Software/website/templates/items.html
{% extends "base.html" %}

{% block title %}Items{% endblock %}

{% block content %}
  <h2 class="mt-4 mb-4">Item Management</h2>

  <!-- Add Item Form -->
  <form method="POST" action="{{ url_for('views.items') }}" class="mb-4">
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="itemName">Item Name</label>
        <input type="text" class="form-control" id="itemName" name="itemName" required>
      </div>
      <div class="form-group col-md-4">
        <label for="price">Price</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">£</span>
          </div>
          <input type="text" class="form-control" id="price" name="price" required>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label for="manufacturer">Manufacturer</label>
        <input type="text" class="form-control" id="manufacturer" name="manufacturer" required>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Add Item</button>
  </form>

  <!-- Display Existing Items with Delete Buttons -->
<h3 class="mt-4 mb-4">Existing Items</h3>
{% for item in items %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ item.itemName }}</h5>
      <p class="card-text">
        Price: £{{ "{:.2f}".format(item.price) }} |
        Manufacturer: {{ item.manufacturer }} |
        Created By: {{ item.user_relationship.first_name if item.user_relationship else 'Unknown' }}
      </p>
      <form method="POST" action="{{ url_for('views.delete_item') }}" class="d-inline">
        <input type="hidden" name="deleteItemName" value="{{ item.itemName }}">
        <input type="hidden" name="deleteManufacturer" value="{{ item.manufacturer }}">
        <button type="submit" class="btn btn-danger">Delete</button>
      </form>
    </div>
  </div>
{% endfor %}
{% endblock %}

Stock Management Software/website/templates/lead_time.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    <label for="order_date">Order Date:</label>
    <input type="date" name="order_date" id="order_date"><br>
    
    <label for="estimated_arrival_date">Estimated Arrival Date:</label>
    <input type="date" name="estimated_arrival_date" id="estimated_arrival_date"><br>
  
    <label for="average_demand_per_day">Average Demand per Day:</label>
    <input type="number" name="average_demand_per_day" id="average_demand_per_day"><br>
  
    <label for="buffer_stock">Buffer Stock Quantity:</label>
    <input type="number" name="buffer_stock" id="buffer_stock"><br>

    <label for="current_stock">Current Stock Quantity:</label>
    <input type="number" name="current_stock" id="current_stock"><br>
  
    <button type="submit" name="calculate">Calculate Difference</button>
</form>

{% if difference_in_days is defined %}
    <p>Difference in Days: {{ difference_in_days }}</p>
    <p>Current Stock Expected to Run Out: {{ current_stock_run_out }}</p>
    <p>Recommendation: {{ recommendation }}</p>
    <p>Order Stock {{ order_recommendation }} days before expected arrival to avoid stockouts.</p>
{% endif %}
{% endblock %}

Stock Management Software/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Stock Management Software/website/templates/promotion.html
{% extends "base.html" %}

{% block title %}
  Promotion
{% endblock %}

{% block content %}
  <h1>Promotion</h1>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Job Role</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for user in general_staff_users %}
          <tr>
            <td>{{ user.email }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.job_role }}</td>
            <td>
              <form action="{{ url_for('views.promote_user') }}" method="POST">
                <input type="hidden" name="email" value="{{ user.email }}">
                <button type="submit" class="btn btn-info">Promote</button>
            </form>
            
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

Stock Management Software/website/templates/transfer.html
{% extends "base.html" %}

{% block title %}Transfer Items{% endblock %}

{% block content %}
<h2 class="mt-4 mb-4">Transfer Items</h2>

<!-- Inventory Table -->
<h3 class="mt-4 mb-2">Inventory</h3>
<form method="post" action="{{ url_for('views.transfer') }}">
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Quantity Available</th>
                <th>Quantity to Transfer</th>
                <th>Select</th>
            </tr>
        </thead>
        <tbody>
            {% for inventory_item in inventory_items %}
            <tr>
                <td>{{ inventory_item.item.itemName }}</td>
                <td>{{ inventory_item.quantity }}</td>
                <td>
                    <input type="number" name="quantity_{{ inventory_item.id }}" value="1" min="1">
                </td>
                <td>
                    <label>
                        <input type="checkbox" name="selectedItems" value="{{ inventory_item.id }}">
                    </label>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Transfer Button -->
    <button type="submit" class="btn btn-primary">Add to Selected Items</button>
</form>



<!-- Selected Items Table -->
<h3 class="mt-4 mb-2">Selected Items</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Item Name</th>
            <th>Quantity to Transfer</th>
        </tr>
    </thead>
    <tbody>
        {% for selected_item in selected_items %}
        <tr>
            <td>{{ selected_item['inventory_item'].item.itemName }}</td>
            <td>{{ selected_item['quantity'] }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Transfer to For Sale Button -->
<form method="post" action="{{ url_for('views.transfer_to_for_sale') }}">
    {% for selected_item in selected_items %}
        <input type="hidden" name="selectedItems" value="{{ selected_item['inventory_item'].id }}">
        <input type="hidden" name="quantity_{{ selected_item['inventory_item'].id }}" value="{{ selected_item['quantity'] }}">
    {% endfor %}
    <button type="submit" class="btn btn-success mt-4">Transfer to For Sale</button>
</form>

{% endblock %}